InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/OrganizationAdmin/Controllers/OrgAssetController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_ONION_PROJECT.APPLICATION.DTo_s.AssetCategoryDtos;
using MVC_ONION_PROJECT.APPLICATION.DTo_s.OrgAssetDtos;
using MVC_ONION_PROJECT.APPLICATION.Services.AssetCategoryService;
using MVC_ONION_PROJECT.APPLICATION.Services.EnumHelpers;
using MVC_ONION_PROJECT.APPLICATION.Services.OrgAssetService;
using MVC_ONION_PROJECT.DOMAIN.ENTITIES;
using MVC_ONION_PROJECT.DOMAIN.ENUMS;
using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Models.AssetCategoryVms;
using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Models.DepartmentVms;
using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Models.EmployeeVms;
using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Models.OrgAssetVms;

namespace MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Controllers
{
    public class OrgAssetController : OrganizationAdminBaseController
    {
        private readonly IOrgAssetService _orgAssetService;
        private readonly IAssetCategoryService _assetCategoryService;
        private readonly IEnumHelperService _enumhelper;
        private readonly IMapper _mapper;

        public OrgAssetController(IOrgAssetService orgAssetService, IMapper mapper, IAssetCategoryService assetCategoryService, IEnumHelperService enumhelper)
        {
            _orgAssetService = orgAssetService;
            _mapper = mapper;
            _assetCategoryService = assetCategoryService;
            _enumhelper = enumhelper;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _orgAssetService.GetAllAsync();

            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<List<OrgAssetListVm>>(result.Data));
            }
            var orgAssetListVm = _mapper.Map<List<OrgAssetListVm>>(result.Data);
            foreach (var item in orgAssetListVm)
            {
                var category = await _assetCategoryService.GetByIdAsync(item.CategoryId);
                item.CategoryName = category.Data.CategoryName;
            }
           
            return View(orgAssetListVm);

        }

        [HttpGet]
        public async Task<IActionResult> AddOrgAsset()
        {
            OrgAssetCreateVm vm = new OrgAssetCreateVm()
            {
                CategoryList = await GetCategorySelectListAsync(),
                PurchaseDate = DateTime.Now
            };
            if (vm.CategoryList is null)
            {
                ErrorNoty("Kategori Olmadan Organizasyona Demirbaş Atayamazsınız");
                return RedirectToAction("index");
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrgAsset(OrgAssetCreateVm model)
        {
            if (!ModelState.IsValid)
            {
                model.CategoryList = await GetCategorySelectListAsync();
                return View(model);
            }
                
            var addResult = await _orgAssetService.AddAsync(_mapper.Map<OrgAssetCreateDto>(model));
            if (!addResult.IsSuccess)
            {
                ErrorNoty(addResult.Message);
                model.CategoryList = await GetCategorySelectListAsync();
                return View(model);
            }
            SuccessNoty(addResult.Message);
            return RedirectToAction(nameof(Index));
        }

        private async Task<SelectList?> GetCategorySelectListAsync()
        {
            var category = await _assetCategoryService.GetAllAsync();
            if (!category.IsSuccess)
            {
                return null;
            }

            return new SelectList(category.Data.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.CategoryName
            }), "Value", "Text");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _orgAssetService.DeleteAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return RedirectToAction(nameof(Index));
            }
            SuccessNoty(result.Message);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EditOrgAsset(Guid id)
        {
            var result = await _orgAssetService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<OrgAssetUpdateVm>(result.Data));
            }
            var orgAssetEditVm = _mapper.Map<OrgAssetUpdateVm>(result.Data);
            orgAssetEditVm.CategoryList= await GetCategorySelectListAsync();
            orgAssetEditVm.AssetStatusList= GetAssetStatusSelectList();
            return View(orgAssetEditVm);
        }

        [HttpPost]
        public async Task<IActionResult> EditOrgAsset(OrgAssetUpdateVm model)
        {
            if (!ModelState.IsValid)
            {
                model.CategoryList = await GetCategorySelectListAsync();
                model.AssetStatusList = GetAssetStatusSelectList();
                return View(model);
            }
                
            var orgAssetEditDto = _mapper.Map<OrgAssetUpdateDto>(model);
            var result = await _orgAssetService.UpdateAsync(orgAssetEditDto);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                model.CategoryList = await GetCategorySelectListAsync();
                model.AssetStatusList = GetAssetStatusSelectList();
                return View(model);
            }
            SuccessNoty(result.Message);
            return RedirectToAction(nameof(Index));
        }

        private SelectList GetAssetStatusSelectList()
        {
            var enumValues = Enum.GetValues(typeof(AssetStatus))
                            .Cast<AssetStatus>().ToList();

            return new SelectList(enumValues.Select(x => new SelectListItem
            {
                Value = x.ToString(),
                Text = _enumhelper.GetDisplayName(x)
            }), "Value", "Text");
        }

        public async Task<IActionResult> DetailsOrgAsset (Guid id)
        {
            var result = await _orgAssetService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<OrgAssetDetailsVm>(result.Data));
            }
            SuccessNoty(result.Message);
            var orgAssetDetailVm = _mapper.Map<OrgAssetDetailsVm>(result.Data);
            var Category = await _assetCategoryService.GetByIdAsync(result.Data.CategoryId);
            orgAssetDetailVm.CategoryName = Category.Data.CategoryName;
            return View(orgAssetDetailVm);
        }
    }
}

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/OrganizationAdmin/Views/OrgAsset/AddOrgAsset.cshtml
@model MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Models.OrgAssetVms.OrgAssetCreateVm;
@{
    Layout = "_Layout";
}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Demirbaş Listesi</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="OrgAsset" asp-action="Index">Demirbaşlar </a></li>
                <li class="breadcrumb-item active">Demirbaş Ekle</li>
            </ul>
        </div>
    </div>
</div>
<form asp-area="OrganizationAdmin" enctype="multipart/form-data" asp-controller="OrgAsset" asp-action="AddOrgAsset">
    <div class="row">
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="SerialNumber" class="control-label">
                </label>
                <input asp-for="SerialNumber" class="form-control" type="text">
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="Name" class="control-label">
                </label>
                <input asp-for="Name" class="form-control" type="text">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="Price" class="control-label">
                </label>
                <input asp-for="Price" class="form-control" type="text">
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>

        

        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="PurchaseDate" class="control-label">
                </label>
                <input asp-for="PurchaseDate" class="form-control" type="date">
                <span asp-validation-for="PurchaseDate" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" asp-items="Model.CategoryList" class="select">
                    <option selected>Seçiniz..</option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger "></span>
            </div>
        </div>

        
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="Description" class="control-label">
                </label>
                <textarea asp-for="Description" rows="5" class="form-control floating"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <button class="btn btn-primary" type="submit"><i class="fa-solid fa-plus"></i> Ekle</button>
        <a class="btn btn-secondary" asp-area="OrganizationAdmin" asp-controller="OrgAsset" asp-action="index"><i class="fa-regular fa-circle-xmark"></i>  İptal</a>
    </div>
</form>

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/OrganizationAdmin/Views/OrgAsset/DetailsOrgAsset.cshtml
@using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Models.OrgAssetVms;
@model OrgAssetDetailsVm;
@{
    Layout = "_Layout";
}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Demirbaş Listesi</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="OrgAsset" asp-action="Index">Demirbaşlar </a></li>
                <li class="breadcrumb-item active">Demirbaş Detayları</li>
            </ul>
        </div>
    </div>
</div>
<div>
    <div class="card col-md-8">
        <div class="card-body px-3">
            <dl class="row">

                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.SerialNumber)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.SerialNumber)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Price)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Price)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.PurchaseDate)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.PurchaseDate)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.CategoryName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CategoryName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Description)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.AssetStatus)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.AssetStatus)
                </dd>



            </dl>
            <div>
                <a class="btn btn-warning" asp-controller="OrgAsset" asp-action="EditOrgAsset" asp-route-id="@Model?.Id"><i class="fa-solid fa-pencil m-r-5"></i> Güncelle</a>

                <a class="btn btn-info" asp-action="Index"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Geri Dön</a>

            </div>
        </div>
    </div>
</div>

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/OrganizationAdmin/Views/OrgAsset/EditOrgAsset.cshtml
@using MVC_ONION_PROJECT.APPLICATION.Services.EnumHelpers;
@model MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Models.OrgAssetVms.OrgAssetUpdateVm;
@inject IEnumHelperService enumhelper;
@{
    Layout = "_Layout";
}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Demirbaş Listesi</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="OrgAsset" asp-action="Index">Demirbaşlar </a></li>
                <li class="breadcrumb-item active">Demirbaş Güncelle</li>
            </ul>
        </div>
    </div>
</div>
<form asp-area="OrganizationAdmin" enctype="multipart/form-data" asp-controller="OrgAsset" asp-action="EditOrgAsset">
    <div class="row">
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="SerialNumber" class="control-label">
                </label>
                <input asp-for="SerialNumber" class="form-control" type="text">
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="Name" class="control-label">
                </label>
                <input asp-for="Name" class="form-control" type="text">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="Price" class="control-label">
                </label>
                <input asp-for="Price" class="form-control" type="text">
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="PurchaseDate" class="control-label">
                </label>
                <input asp-for="PurchaseDate" class="form-control" type="date">
                <span asp-validation-for="PurchaseDate" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="CategoryId" class="control-label">
                </label>
                <select asp-for="CategoryId" asp-items="Model.CategoryList" class="select">
                    <option selected>Seçiniz..</option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="AssetStatus" class="control-label">
                </label>
                <select asp-for="AssetStatus" asp-items="Model.AssetStatusList" class="select">
                    <option selected>Seçiniz..</option>
                </select>
                <span asp-validation-for="AssetStatus" class="text-danger"></span>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="Description" class="control-label">
                </label>
                <textarea asp-for="Description" rows="5" class="form-control floating"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <button class="btn btn-primary" type="submit"><i class="fa-solid fa-pencil m-r-5"></i>  Güncelle</button>
        <a class="btn btn-secondary" asp-area="OrganizationAdmin" asp-controller="OrgAsset" asp-action="index"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Geri Dön</a>
    </div>
</form>

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/OrganizationAdmin/Views/OrgAsset/Index.cshtml
@using MVC_ONION_PROJECT.DOMAIN.ENUMS;
@using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Models.OrgAssetVms;
@model List<OrgAssetListVm>

@{
    Layout = "_Layout";
}


<div class="content container-fluid">

    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">Demirbaş Listesi</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                    <li class="breadcrumb-item active">Demirbaşlar</li>
                </ul>
            </div>
            <div class="col-auto float-end ms-auto">
                <a class="btn btn-secondary" asp-area="OrganizationAdmin" asp-controller="OrgAsset" asp-action="AddOrgAsset"><i class="fa-solid fa-plus"></i>Demirbaş Ekle</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div>
                <table class="table table-striped custom-table mb-0" id="OrgAssetLisTable">
                    <thead>
                        <tr>
                            <th class="width-thirty">No</th>
                            <th>Seri No</th>
                            <th>Demirbaş Adı </th>
                            <th>Alım Tarihi </th>
                            <th>Kategori </th>
                            <th class="text-center">Durumu </th>
                            <th class="text-end">İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@(Model.IndexOf(item) + 1)</td>
                                    <td>@item.SerialNumber</td>
                                    <td>@item.Name</td>
                                    <td>@item.PurchaseDate.ToShortDateString()</td>
                                    <td>@item.CategoryName</td>
                                    <td class="text-center">
                                        @if (item.AssetStatus == AssetStatus.PendingApproval)
                                        {
                                            <span class="badge bg-inverse-info">Onayda</span>
                                        }
                                        @if (item.AssetStatus == AssetStatus.Assigned)
                                        {
                                            <span class="badge bg-inverse-success">Atandı</span>
                                        }
                                        @if (item.AssetStatus == AssetStatus.Rejected)
                                        {
                                            <span class="badge bg-inverse-danger">İptal Edildi</span>
                                        }
                                        @if (item.AssetStatus == AssetStatus.Returned)
                                        {
                                            <span class="badge bg-inverse-primary">Geri Alındı</span>
                                        }
                                        @if (item.AssetStatus == AssetStatus.NotAssigned)
                                        {
                                            <span class="badge bg-inverse-info">Atanmadı</span>
                                        }
                                    </td>
                                    <td class="text-end">
                                        <div class="dropdown dropdown-action">
                                            <a href="#" class="action-icon dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="material-icons">more_vert</i></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <!-- Edit Button -->
                                                <a class="dropdown-item" h asp-controller="OrgAsset" asp-action="EditOrgAsset" asp-route-id="@item.Id"><i class="fa-solid fa-pencil m-r-5"></i> Güncelle</a>
                                                <!-- Details Button -->
                                                <a class="dropdown-item" h asp-controller="OrgAsset" asp-action="DetailsOrgAsset" asp-route-id="@item.Id"><i class="fa-solid fa-eye m-r-5"></i> Detaylar</a>

                                                <!-- Delete Button -->
                                                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#delete_OrgAsset_@item.Id"><i class="fa-regular fa-trash-can m-r-5"></i> Sil</a>
                                            </div>
                                        </div>
                                    </td>


                                </tr>

                                <!-- Delete Modal -->
                                <div class="modal custom-modal fade" id="delete_OrgAsset_@item.Id" role="dialog">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-body">
                                                <div class="form-header">
                                                    <h3>Demirbaş Silme İşlemi</h3>
                                                    <p>"@item.Name" demirbaş kaydını silmek istediğinize emin misiniz?</p>
                                                </div>
                                                <div class="modal-btn delete-action">
                                                    <div class="row">
                                                        <div class="offset-2 col-3">
                                                            <!-- Delete Button with Form Submission -->
                                                            <form method="post" asp-controller="OrgAsset" asp-action="Delete" asp-route-id="@item.Id">
                                                                <button type="submit" class="btn btn-primary"><i class="fa-regular fa-trash-can m-r-5"> </i> Sil</button>
                                                            </form>
                                                        </div>
                                                        <div class="offset-2 col-3">
                                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa-regular fa-circle-xmark"></i>  İptal</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            // Sayfa yüklendiğinde DataTable'ı oluştur
            $('#OrgAssetLisTable').DataTable();

            // Sayfa ilk açıldığında verileri yükleme işlemi
        });
    </script>
    }