InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/Employee/Controllers/EmployeeReimbursementController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVC_ONION_PROJECT.APPLICATION.DTo_s.AdvancePaymentDtos;
using MVC_ONION_PROJECT.APPLICATION.DTo_s.ReimbursementDtos;
using MVC_ONION_PROJECT.APPLICATION.Services.AddImageServices;
using MVC_ONION_PROJECT.APPLICATION.Services.EmailHelper;
using MVC_ONION_PROJECT.APPLICATION.Services.EmailServices;
using MVC_ONION_PROJECT.APPLICATION.Services.EmployeeServicces;
using MVC_ONION_PROJECT.APPLICATION.Services.ReimbursementService;
using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.EmployeeAdvanceVms;
using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.EmployeeReimbursementVms;
using System.Security.Claims;

namespace MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Controllers
{
    public class EmployeeReimbursementController : EmployeeBaseController
    {
        private readonly IReimbursementService _reimbursementService;
        private readonly IMapper _mapper;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IEmployeeService _employeeService;
        private readonly IEmailService _emailService;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IAddImageService _addImageService;
        private readonly IEmailHelper _emailHelper;

        public EmployeeReimbursementController(IReimbursementService reimbursementService, IMapper mapper, IHttpContextAccessor contextAccessor, IEmployeeService employeeService, IEmailService emailService, SignInManager<IdentityUser> signInManager, IAddImageService addImageService, IEmailHelper emailHelper)
        {
            _reimbursementService = reimbursementService;
            _mapper = mapper;
            _contextAccessor = contextAccessor;
            _employeeService = employeeService;
            _emailService = emailService;
            _signInManager = signInManager;
            _addImageService = addImageService;
            _emailHelper = emailHelper;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _reimbursementService.GetAllAsync();
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<List<EmployeeReimbursementListVm>>(result.Data));
            }
            var identityId = _contextAccessor?.HttpContext?.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userReimbursementListVM = await _reimbursementService.GetListOfMineReimbursement(identityId);
            return View(_mapper.Map<List<EmployeeReimbursementListVm>>(userReimbursementListVM.Data));
        }

        [HttpGet]
        public IActionResult AddReimbursement()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddReimbursement(EmployeeReimbursementCreateVm model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var userId = _contextAccessor?.HttpContext?.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employee = await _employeeService.GetByidentityIdAsync(Guid.Parse(userId));
            model.EmployeeId = employee.Data.Id;
            model.PaymentStatus = DOMAIN.ENUMS.PaymentStatus.Pending;
            var pathname = await _addImageService.AddImage(model.ExpenseAttachmentsfile);
            if (pathname==null)
            {
                ErrorNoty("Lütfen Fatura Resmi Ekleyin");
                return View(model);
            }
            model.ExpenseAttachmentspath = pathname;
            var addResult = await _reimbursementService.AddAsync(_mapper.Map<ReimbursementCreateDto>(model));
            if (!addResult.IsSuccess)
            {
                ErrorNoty(addResult.Message);
                return View(model);
            }
            var mail = await _emailHelper.HarcamaMailIstek(employee.Data.Name, employee.Data.Surname, addResult.Data.Amount);

            await _emailService.SendMail("Harcama Talebi Hk.", mail, "cem.sener@bilgeadamboost.com");
            SuccessNoty(addResult.Message);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _reimbursementService.DeleteAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return RedirectToAction(nameof(Index));
            }
            SuccessNoty(result.Message);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EditReimbursement(Guid id)
        {
            var result = await _reimbursementService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<EmployeeReimbursementUpdateVm>(result.Data));
            }
            if (result.Data.PaymentStatus != DOMAIN.ENUMS.PaymentStatus.Pending)
            {
                ErrorNoty("Cevaplanmış talep değiştirilemez.");
                return RedirectToAction(nameof(Index));
            }
            var categoryEditVm = _mapper.Map<EmployeeReimbursementUpdateVm>(result.Data);
            return View(categoryEditVm);
        }
        [HttpPost]

        public async Task<IActionResult> EditReimbursement(EmployeeReimbursementUpdateVm model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var categoryeditdto = _mapper.Map<ReimbursementUpdateDto>(model);
            categoryeditdto.PaymentStatus = DOMAIN.ENUMS.PaymentStatus.Pending;
            var pathname = await _addImageService.AddImage(model.ExpenseAttachmentsfile);
            if (pathname == null)
            {
                ErrorNoty("Lütfen Fatura Resmi Ekleyin");
                return View(model);
            }
            categoryeditdto.ExpenseAttachmentspath= pathname;
            var result = await _reimbursementService.UpdateAsync(categoryeditdto);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(model);
            }
            SuccessNoty(result.Message);
            var resultVM = _mapper.Map<EmployeeReimbursementUpdateVm>(result.Data);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DetailsReimbursement(Guid id)
        {
            var result = await _reimbursementService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<EmployeeReimbursementDetailsVm>(result.Data));
            }
            SuccessNoty(result.Message);
            var paymentDetailVm = _mapper.Map<EmployeeReimbursementDetailsVm>(result.Data);
            return View(paymentDetailVm);
        }
    }
}

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/Employee/Views/EmployeeReimbursement/AddReimbursement.cshtml
@using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.EmployeeReimbursementVms;
@model EmployeeReimbursementCreateVm;

@{
    Layout = "_Layout";
}

<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Masraflar</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="EmployeeReimbursement" asp-action="Index">Masraflar</a></li>
                <li class="breadcrumb-item active">Yeni Masraf Talebi</li>
            </ul>
        </div>
    </div>
</div>
<form asp-area="Employee" enctype="multipart/form-data" asp-controller="EmployeeReimbursement" asp-action="AddReimbursement">
    <div class="col-sm-6">
        <div class="input-block mb-3">
            <label asp-for="Currency" class="col-form-label"></label>
            <select asp-for="Currency" class="form-control select">
                <option value="none" selected>Seçiniz..</option>
                <option value="USD">Dolar</option>
                <option value="TRY">Türk Lirası</option>
                <option value="EUR">Euro</option>
            </select>
            <span asp-validation-for="Currency" class="text-danger"></span>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="input-block mb-3">
            <label asp-for="Date" class="control-label">
            </label>
            <input asp-for="Date" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="form-control" type="date">
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>
    </div>
    <div class="col-sm-6 mt-3">
        <div class="col-sm-6 ">
            <div class="input-block mb-3">
                <label for="fileInput" class="row align-items-center">
                    <label class="col-2" asp-for="ExpenseAttachmentsfile"></label>
                    <img class="img5 offset-2 col-2 " id="uploadedImage" src="/uploads/plus-icon.png" alt="Yüklenen Resim">
                </label>
                <input asp-for="ExpenseAttachmentsfile" id="fileInput" hidden type="file" accept="image/*" />
                <span asp-validation-for="ExpenseAttachmentsfile" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12 mb-4">
        <div class="input-block mb-3 form-focus marrg">
            <input asp-for="Amount" type="number"  class="form-control floating">
            <label asp-for="Amount" class="focus-label">Masraf Miktarı</label>
            <span asp-validation-for="Amount" class="text-danger"></span>
        </div>
    </div>


    <div class="col-md-6 col-sm-12 mb-5">
        <div class="input-block mb-3 form-focus ">
            <textarea asp-for="Description" rows="5" class="form-control floating"></textarea>
            <label asp-for="Description" class="focus-label"></label>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>

    <div class="col-md-6 col-sm-12">
        <button class="btn btn-primary" type="submit"><i class="fa-solid fa-plus"></i>Ekle</button>
        <a class="btn btn-secondary" asp-area="Employee" asp-controller="EmployeeReimbursement" asp-action="Index"> <i class="fa fa-arrow-left" aria-hidden="true"></i>  Geri Dön</a>
    </div>
</form>

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/Employee/Views/EmployeeReimbursement/DetailsReimbursement.cshtml
@using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.EmployeeReimbursementVms;
@model EmployeeReimbursementDetailsVm;
@{
    Layout = "_Layout";
}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Masraflar</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="EmployeeReimbursement" asp-action="Index">Masraflar</a></li>
                <li class="breadcrumb-item active">Masraf Detayları</li>
            </ul>
        </div>
    </div>
</div>
<div>
    <div class="card col-md-8">
        <div class="card-body px-5">
            <dl class="row mt-3">
  
                    <dt class="col-md-4 col-sm-12">
            @{
                string encodedData = Convert.ToBase64String(Model?.ExpenseAttachments ?? new byte[0]);
            }
            <img src="data:image/jpeg;base64,@(encodedData)" >
                </dt>
                <dl class="col-md-8 col-sm-12 mt-sm-2 px-4">
                <dt class="col-6">
                    @Html.DisplayNameFor(model => model.Date.ToLongDateString())
                </dt>
                <dd class="col-6">
                    @Html.DisplayFor(model => model.Date.ToShortDateString())
                </dd>
                    <dt class="col-6">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                    <dd class="col-6">
                    @Html.DisplayFor(model => model.Description)
                </dd>
                    <dt class="col-6">
                    @Html.DisplayNameFor(model => model.Amount)
                </dt>
                    <dd class="col-6">
                    @Html.DisplayFor(model => model.Amount)
                </dd>
                    <dt class="col-6">
                    @Html.DisplayNameFor(model => model.PaymentStatus)
                </dt>
                    <dd class="col-6">
                    @Html.DisplayFor(model => model.PaymentStatus)
                </dd>
            </dl>
            </dl>
            <div>
                <a class="btn btn-primary" asp-controller="EmployeeReimbursement" asp-action="EditReimbursement" asp-route-id="@Model.Id">Düzenle</a>

                <a class="btn btn-secondary" asp-action="Index"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Geri Dön</a>

            </div>
        </div>
    </div>
</div>

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/Employee/Views/EmployeeReimbursement/EditReimbursement.cshtml
@using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.EmployeeReimbursementVms;
@model EmployeeReimbursementUpdateVm;

@{
    Layout = "_Layout";
}

<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Masraflar</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="EmployeeReimbursement" asp-action="Index">Masraflar</a></li>
                <li class="breadcrumb-item active">Masraf Düzenleme</li>
            </ul>
        </div>
    </div>
</div>
<form asp-area="Employee" enctype="multipart/form-data" asp-controller="EmployeeReimbursement" asp-action="EditReimbursement">
    <div class="col-sm-6">
        <div class="input-block mb-3">
            <label asp-for="Currency" class="col-form-label"></label>
            <select asp-for="Currency" class="form-control select">
                <option selected>Seçiniz..</option>
                <option value="USD">Dolar</option>
                <option value="TRY">Türk Lirası</option>
                <option value="EUR">Euro</option>
            </select>
            <span asp-validation-for="Currency" class="text-danger"></span>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="input-block mb-3">
            <label asp-for="Date" class="control-label">
            </label>
            <input asp-for="Date" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="form-control" type="date">
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>
    </div>
    <div class="col-sm-6 ">
        <div class="input-block mb-3">
            <label for="fileInput" class="row align-items-center">
                <label class="col-2" asp-for="ExpenseAttachmentsfile"></label>
                <img class="img5 offset-2 col-2 " id="uploadedImage" src="/uploads/plus-icon.png" alt="Yüklenen Resim">
            </label>
            <input asp-for="ExpenseAttachmentsfile" id="fileInput" hidden type="file" accept="image/*" />
            <span asp-validation-for="ExpenseAttachmentsfile" class="text-danger"></span>
        </div>
    </div>
    <div class="col-md-6 col-sm-12 mb-4">
        <div class="input-block mb-3 form-focus marrg">
            <input asp-for="Amount" type="number" class="form-control floating">
            <label asp-for="Amount" class="focus-label">Masraf Miktarı</label>
            <span asp-validation-for="Amount" class="text-danger"></span>
        </div>
    </div>
    <div class="col-md-6 col-sm-12 mb-5">
        <div class="input-block mb-3 form-focus ">           
            <input asp-for="Id" hidden type="text" class="form-control floating">
            <input asp-for="EmployeeId" hidden type="text" class="form-control floating">
            <textarea asp-for="Description" rows="5" class="form-control floating"></textarea>
            <label asp-for="Description" class="focus-label"></label>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>

    <div class="col-md-6 col-sm-12">
        <button class="btn btn-primary" type="submit"><i class="fa-solid fa-pencil m-r-5"></i> Güncelle</button>
        <a class="btn btn-secondary" asp-area="Employee" asp-controller="EmployeeReimbursement" asp-action="Index"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Geri Dön</a>
    </div>
</form>

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/Employee/Views/EmployeeReimbursement/Index.cshtml
@using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.EmployeeReimbursementVms
@using MVC_ONION_PROJECT.DOMAIN.ENUMS;
@model List<EmployeeReimbursementListVm>;

@{
    Layout = "_Layout";
}

<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Masraflar</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item active">Masraflar</li>
            </ul>
        </div>
        <div class="col-auto float-end ms-auto">
            <a class="btn add-btn" asp-controller="EmployeeReimbursement" asp-action="AddReimbursement"><i class="fa-solid fa-plus"></i>Harcama Talebi Oluştur</a>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="table">
            <table class="table table-striped custom-table leave-employee-table mb-0 ">
                <thead>
                    <tr>
                        <th>Sıra</th>
                        <th>Masraf Miktarı</th>
                        <th>Açıklama</th>
                        <th class="text-center">Durumu</th>
                        <th class="text-end">Eylemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {            
                        decimal tutar = item.Amount; 
                        string formatliTutar = string.Format("{0:C}", tutar);
                        <tr>
                            <td>@(Model.IndexOf(item) + 1)</td>  
                            <td>@formatliTutar</td>
                            <td>@item.Description</td>
                            <td class="text-center">
                                @if (item.PaymentStatus == PaymentStatus.Pending)
                                {
                                    <span class="badge bg-inverse-info">Onayda</span>
                                }
                                @if (item.PaymentStatus == PaymentStatus.Rejected)
                                {
                                    <span class="badge bg-inverse-danger">İptal Edildi</span>
                                }
                                @if (item.PaymentStatus == PaymentStatus.Accepted)
                                {
                                    <span class="badge bg-inverse-info">Onaylandı</span>
                                }
                            </td>
                            @* <td>
                        <div class="action-label">
                        <a class="btn btn-white btn-sm btn-rounded" href="javascript:void(0);">
                        <i class="fa-regular fa-circle-dot"></i> @item.ReturnStatus.ToString()
                        </a>
                        </div>
                        </td> *@
                            @*<td>
                        <h2 class="table-avatar">
                        <a href="profile.html" class="avatar avatar-xs"><img src="assets/img/profiles/avatar-09.jpg" alt="User Image"></a>
                        <a href="#"></a>
                        </h2>
                        </td>*@
                            <td class="text-end">
                                <div class="dropdown dropdown-action">
                                    <a href="#" class="action-icon dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="material-icons">more_vert</i></a>
                                    <div class="dropdown-menu dropdown-menu-right">

                                        <a class="dropdown-item" asp-controller="EmployeeReimbursement" asp-action="EditReimbursement" asp-route-id="@item.Id"><i class="fa-solid fa-pencil m-r-5"></i> Düzenle</a>

                                        <a class="dropdown-item" asp-controller="EmployeeReimbursement" asp-action="DetailsReimbursement" asp-route-id="@item.Id"><i class="fa-regular fa-eye m-r-5"></i>Detaylar</a>

                                        <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#delete_advancepayment_@item.Id"><i class="fa-regular fa-trash-can m-r-5"></i>Sil</a>

                                    </div>
                                </div>
                            </td>
                        </tr>
                        <!-- Delete Modal -->
                        <div class="modal custom-modal fade" id="delete_advancepayment_@item.Id" role="dialog">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-body">
                                        <div class="form-header">
                                            <h3>Masraf Talebi Sil</h3>
                                            <p>Bu masraf talebini silmek istiyor musunuz?</p>
                                        </div>
                                        <div class="modal-btn delete-action">
                                            <div class="row">
                                                <div class="offset-2 col-3">
                                                    <!-- Delete Button with Form Submission -->
                                                    <form method="post" asp-controller="EmployeeReimbursement" asp-action="Delete" asp-route-id="@item.Id">
                                                        <button type="submit" class="btn btn-primary"><i class="fa-regular fa-trash-can m-r-5"> </i> Sil</button>
                                                    </form>
                                                </div>
                                                <div class="offset-2 col-3">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa-regular fa-circle-xmark"></i>  İptal</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>