InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/Employee/Controllers/EmployeTimeOffController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC_ONION_PROJECT.APPLICATION.DTo_s.DepartmentDtos;
using MVC_ONION_PROJECT.APPLICATION.DTo_s.TimeOffDtos;
using MVC_ONION_PROJECT.APPLICATION.Services.EmailHelper;
using MVC_ONION_PROJECT.APPLICATION.Services.EmailServices;
using MVC_ONION_PROJECT.APPLICATION.Services.EmployeeServicces;
using MVC_ONION_PROJECT.APPLICATION.Services.EnumHelpers;
using MVC_ONION_PROJECT.APPLICATION.Services.TimeOffServices;
using MVC_ONION_PROJECT.APPLICATION.Services.TimeOffTypeService;
using MVC_ONION_PROJECT.DOMAIN.ENUMS;
using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.TimeOffVms;
using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Models.DepartmentVms;
using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.OrganizationAdmin.Models.TimeOffVms;
using System.Security.Claims;
using TimeOffListVm = MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.TimeOffVms.TimeOffListVm;

namespace MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Controllers
{
    public class EmployeTimeOffController : EmployeeBaseController
    {
        private readonly ITimeOffService _timeOffService;
        private readonly ITimeOffTypeService _timeOffTypeService;
        private readonly IMapper _mapper;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly IHttpContextAccessor _contextAccessor;
        private readonly IEmployeeService _employeeService;
        private readonly IEmailService _emailService;
        private readonly IEnumHelperService _enumHelperService;
        private readonly IEmailHelper _emailHelper;

        public EmployeTimeOffController(ITimeOffService timeOffService, IMapper mapper, SignInManager<IdentityUser> signInManager, ITimeOffTypeService timeOffTypeService, IEmployeeService employeeService, IHttpContextAccessor contextAccessor, IEmailService emailService, IEnumHelperService enumHelperService, IEmailHelper emailHelper)
        {
            _timeOffService = timeOffService;
            _mapper = mapper;
            _signInManager = signInManager;
            _timeOffTypeService = timeOffTypeService;
            _employeeService = employeeService;
            _contextAccessor = contextAccessor;
            _emailService = emailService;
            _enumHelperService = enumHelperService;
            _emailHelper = emailHelper;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _timeOffService.GetAllAsync();
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<List<TimeOffListVm>>(result.Data));
            }
            var userTimeOffList = result.Data.FindAll(x => x.CreatedBy == _signInManager.Context.User?.FindFirstValue(ClaimTypes.NameIdentifier));
            var userTimeOffListVM = _mapper.Map<List<TimeOffListVm>>(userTimeOffList);
            foreach (var item in userTimeOffListVM)
            {
                var timeOffTypeId = item.TimeOffTypeId;
                var timeOffType = await _timeOffTypeService.GetByIdAsync(timeOffTypeId);
                item.Name = timeOffType.Data.Name;
            }
            return View(userTimeOffListVM);
        }

        [HttpGet]
        public async Task<IActionResult> AddTimeOff()
        {
            TimeOffCreateVm vm = new TimeOffCreateVm()
            {
                TimeOffList = await GetTimeOffSelectListAsync(),
                StartTime = DateTime.Now,
                EndTime = DateTime.Now
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> AddTimeOff(TimeOffCreateVm model, string returnStatusstring)
        {
            if (!ModelState.IsValid)
            {
                model.TimeOffList = await GetTimeOffSelectListAsync();
                return View(model);
            }
            
            var userId = _contextAccessor?.HttpContext?.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var employee = await _employeeService.GetByidentityIdAsync(Guid.Parse(userId));
            model.EmployeeId = employee.Data.Id;
            model.ReturnStatus = DOMAIN.ENUMS.ReturnStatus.Pending;

            if (model.StartTime > model.EndTime)
            {
                ErrorNoty("Başlangıç tarihi bitiş tarihinden önce sonra olamaz.");
                model.TimeOffList = await GetTimeOffSelectListAsync();
                return View(model);
            }

            var addResult = await _timeOffService.AddAsync(_mapper.Map<TimeOffCreateDto>(model));
            if (!addResult.IsSuccess)
            {
                ErrorNoty(addResult.Message);
                model.TimeOffList = await GetTimeOffSelectListAsync();
                return View(model);
            }

            var mailTaslak = await _emailHelper.AvansMailIstek(employee.Data.Name, employee.Data.Surname, model.NumberOfDays);

            await _emailService.SendMail("Yıllık İzin Kullanımı Hk.",mailTaslak, "cem.sener@bilgeadamboost.com");
            SuccessNoty(addResult.Message);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var timeOff = await _timeOffService.GetByIdAsync(id);
            if (timeOff != null && (timeOff.Data.ReturnStatus == DOMAIN.ENUMS.ReturnStatus.Assigned || timeOff.Data.StartTime.Date < DateTime.Now.Date))
            {
                ErrorNoty("Bu izin talebi onaylanmış ve tarihi geçmiş, silinemez.");
                return RedirectToAction(nameof(Index));
            }

            var result = await _timeOffService.DeleteAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return RedirectToAction(nameof(Index));
            }
            SuccessNoty(result.Message);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EditTimeOff(Guid id)
        {
            var result = await _timeOffService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<TimeOffUpdateVm>(result.Data));
            }
            if (result.Data.ReturnStatus != DOMAIN.ENUMS.ReturnStatus.Pending)
            {
                ErrorNoty("Cevaplanmış talep değiştirilemez");
                return RedirectToAction(nameof(Index));
            }
            var timeOffEditVm = _mapper.Map<TimeOffUpdateVm>(result.Data);
            return View(timeOffEditVm);
        }

        [HttpPost]
        public async Task<IActionResult> EditTimeOff(TimeOffUpdateVm model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var timeOffEditDto = _mapper.Map<TimeOffUpdateDto>(model);
            timeOffEditDto.ReturnStatus = ReturnStatus.Pending;

            if (model.StartTime > model.EndTime)
            {
                ErrorNoty("Başlangıç tarihi bitiş tarihinden önce sonra olamaz.");
                return View(model);
            }
  
            var result = await _timeOffService.UpdateAsync(timeOffEditDto);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(model);
            }

            SuccessNoty(result.Message);
            var resultVm = _mapper.Map<TimeOffUpdateVm>(result.Data);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DetailsTimeOff(Guid id)
        {
            var result = await _timeOffService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<TimeOffDetailVm>(result.Data));
            }
            SuccessNoty(result.Message);
            var timeOffDetailVm = _mapper.Map<TimeOffDetailVm>(result.Data);
            return View(timeOffDetailVm);
        }

        private async Task<SelectList> GetTimeOffSelectListAsync()
        {
            var timeOffType = await _timeOffTypeService.GetAllAsync();

            return new SelectList(timeOffType.Data.Select(x => new SelectListItem
            {
                Value = x.Id.ToString(),
                Text = x.Name
            }), "Value", "Text");
        }
    }
}

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/Employee/Views/EmployeTimeOff/AddTimeOff.cshtml
@using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.TimeOffVms;
@model TimeOffCreateVm;

@{
    Layout = "_Layout";
}

<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">İzinler</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="EmployeTimeOff" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="EmployeTimeOff" asp-action="Index">İzinler</a></li>
                <li class="breadcrumb-item active">Yeni İzin</li>
            </ul>
        </div>
    </div>
    <form asp-area="Employee" asp-controller="EmployeTimeOff" asp-action="AddTimeOff">

        <div class="col-md-6 col-sm-12 mb-5">
            <div class="input-block mb-3">
                <label asp-for="StartTime" class="control-label">Başlangıç Tarihi</label>
                <input asp-for="StartTime" class="form-control" type="date">
                <span asp-validation-for="StartTime" class="text-danger"></span>
            </div>
        </div>


        <div class="col-md-6 col-sm-12 mb-5">
            <div class="input-block mb-3">
                <label asp-for="EndTime" class="control-label">Bitiş Tarihi</label>
                <input asp-for="EndTime" class="form-control" type="date">
                <span asp-validation-for="EndTime" class="text-danger"></span>
            </div>
        </div>


        <div class="col-md-6 col-sm-12 mb-5">
            <div class="input-block mb-3 form-focus ">
                <textarea asp-for="Reason" rows="5" class="form-control floating"></textarea>
                <label asp-for="Reason" class="focus-label"></label>
                <span asp-validation-for="Reason" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-6 col-sm-12 mb-5">
            <div class="input-block mb-3">
                <label asp-for="TimeOffTypeId" class="col-form-label"></label>
                <select asp-for="TimeOffTypeId" asp-items="Model.TimeOffList" class="form-control select">
                    <option value="" selected>Seçiniz..</option>
                </select>
                <span asp-validation-for="TimeOffTypeId" class="text-danger"></span>
            </div>
        </div>

        <div class="col-md-6 col-sm-12">
            <button class="btn btn-primary" type="submit">Oluştur</button>
            <a class="btn btn-secondary" asp-area="Employee" asp-controller="EmployeTimeOff" asp-action="Index"> <i class="fa fa-arrow-left" aria-hidden="true"></i>  Geri Dön</a>
        </div>
    </form>

</div>

@* <script>
    function calculateDateDifference() {         // Başlangıç ve bitiş tarihlerini alın
        var startDateString = document.getElementById("StartTime").value;
        var endDateString = document.getElementById("EndTime").value;// Tarihleri JavaScript Date nesnelerine dönüştürün
        var endDatePicker = document.getElementById("EndTime"); endDatePicker.addEventListener("change", calculateDateDifference);
        var startDate = new Date(startDateString);
        var endDate = new Date(endDateString);         // Tarih farkını hesaplayın (milisaniye cinsinden)
        var dateDifference = endDate - startDate;         // Gün cinsinden farkı hesaplayın
        var daysDifference = Math.floor(dateDifference / (1000 * 60 * 60 * 24));         // Sonucu görüntüleyin
        var resultDiv = document.getElementById("NumberOfDays");
        resultDiv.innerHTML = daysDifference;

    }
</script> *@

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/Employee/Views/EmployeTimeOff/DetailsTimeOff.cshtml
@using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.TimeOffVms;
@model TimeOffDetailVm;
@{
    Layout = "_Layout";
}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">İzinler</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="EmployeTimeOff" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="EmployeTimeOff" asp-action="Index">İzinler</a></li>
                <li class="breadcrumb-item active">İzin Detayları</li>
            </ul>
        </div>
    </div>
</div>
<div>
    <div class="card col-md-8">
        <div class="card-body px-3">

            <dl class="row">

                @* <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.StartTime)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.StartTime.ToString("dd.MM.yyyy"))
                </dd>

                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.EndTime)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.EndTime.ToString("dd.MM.yyyy"))
                </dd> *@

                <dt class="col-sm-2">
                    Start Time
                </dt>
                <dd class="col-sm-10">
                    @Model.StartTime.ToString("dd.MM.yyyy")
                </dd>

                <dt class="col-sm-2">
                    End Time
                </dt>
                <dd class="col-sm-10">
                    @Model.EndTime.ToString("dd.MM.yyyy")
                </dd>

                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Reason)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Reason)
                </dd>

                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.NumberOfDays)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.NumberOfDays)
                </dd>

            </dl>
            <div>
                <a class="btn btn-primary" asp-controller="EmployeTimeOff" asp-action="EditTimeOff" asp-route-id="@Model.Id">Düzenle</a>

                <a class="btn btn-secondary" asp-action="Index"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Geri Dön</a>

            </div>
        </div>
    </div>
</div>

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/Employee/Views/EmployeTimeOff/EditTimeOff.cshtml
@model MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.TimeOffVms.TimeOffUpdateVm;
@{
    Layout = "_Layout";
}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">İzinler</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="EmployeTimeOff" asp-action="Index">İzinler</a></li>
                <li class="breadcrumb-item active">İzin Güncelleme</li>
            </ul>
        </div>
    </div>
</div>
<form asp-area="Employee" asp-controller="EmployeTimeOff" asp-action="EditTimeOff">
    
    <div class="col-md-6 col-sm-12 mb-5">
        <div class="input-block mb-3">
            <label asp-for="StartTime" class="control-label">Başlangıç Tarihi</label>
            <input asp-for="StartTime" class="form-control" type="date">
            <span asp-validation-for="StartTime" class="text-danger"></span>
        </div>
    </div>


    <div class="col-md-6 col-sm-12 mb-5">
        <div class="input-block mb-3">
            <label asp-for="EndTime" class="control-label">Bitiş Tarihi</label>
            <input asp-for="EndTime" class="form-control" type="date">
            <span asp-validation-for="EndTime" class="text-danger"></span>
        </div>
    </div>

    <div class="col-md-6 col-sm-12 mb-5">
        <div class="input-block mb-3 form-focus ">
            <input asp-for="Reason" type="text" class="form-control floating">
            <label asp-for="Reason" class="focus-label">Açıklama</label>
            <span asp-validation-for="Reason" class="text-danger"></span>
        </div>
    </div>

    <div class="col-md-6 col-sm-12">
        <button class="btn btn-primary" type="submit"><i class="fa-solid fa-pencil m-r-5"></i> Güncelle</button>
        <a class="btn btn-secondary" asp-area="Employee" asp-controller="EmployeTimeOff" asp-action="index"><i class="fa fa-arrow-left" aria-hidden="true"></i>  Geri Dön</a>
    </div>
</form>

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/Employee/Views/EmployeTimeOff/Index.cshtml
@using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.Employee.Models.TimeOffVms;
@using MVC_ONION_PROJECT.DOMAIN.ENUMS;
@model List<TimeOffListVm>;

@{
    Layout = "_Layout";
}

<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">İzinler</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item active">İzinler</li>
            </ul>
        </div>
        <div class="col-auto float-end ms-auto">
            <a class="btn add-btn" asp-controller="EmployeTimeOff" asp-action="AddTimeOff"><i class="fa-solid fa-plus"></i> İzin Talebi Oluştur</a>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="table">
            <table class="table table-striped custom-table leave-employee-table mb-0" id="myDataTable">
                <thead>
                    <tr>
                        <th>İzin Tipi</th>
                        <th>Başlangıç Tarihi</th>
                        <th>Bitiş Tarihi</th>
                        <th>İzinli Gün Sayısı</th>
                        <th class="text-center">Güncel Durumu</th>
                        @* <th>Approved by</th> *@
                        <th class="text-end">Eylemler</th>
                    </tr>
                </thead>
                <tbody>

                    @if (Model != null)
                    {
                        var sortedModel = Model.OrderByDescending(item => item.StartTime).ToList();
                    
                    @foreach (var item in sortedModel)
                    {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.StartTime.Date.ToShortDateString()</td>
                        <td>@item.EndTime.Date.ToShortDateString()</td>
                        <td>@item.NumberOfDays</td>
                            <td class="text-center">
                                @if (item.ReturnStatus == ReturnStatus.Pending)
                                {
                                    <span class="badge bg-inverse-info">Onayda</span>
                                }
                                @if (item.ReturnStatus == ReturnStatus.Assigned)
                                {
                                    <span class="badge bg-inverse-success">Atandı</span>
                                }
                                @if (item.ReturnStatus == ReturnStatus.Rejected)
                                {
                                    <span class="badge bg-inverse-danger">İptal Edildi</span>
                                }
                                @if (item.ReturnStatus == ReturnStatus.Returned)
                                {
                                    <span class="badge bg-inverse-info">Teslim Alındı</span>
                                }
                            </td>
                        @* <td class="text-center">
                            <div class="action-label">
                                <a class="btn btn-white btn-sm btn-rounded" href="javascript:void(0);">
                                        <i class="fa-regular fa-circle-dot"></i> @item.ReturnStatus.ToString()
                                </a>
                            </div>
                        </td> *@
                        @* <td>
                            <h2 class="table-avatar">
                                <a href="profile.html" class="avatar avatar-xs"><img src="assets/img/profiles/avatar-09.jpg" alt="User Image"></a>
                                <a href="#"></a>
                            </h2>
                        </td> *@
                        <td class="text-end">
                            <div class="dropdown dropdown-action">
                                <a href="#" class="action-icon dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="material-icons">more_vert</i></a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <!--Edit Butonu-->
                                    <a class="dropdown-item" asp-controller="EmployeTimeOff" asp-action="EditTimeOff" asp-route-id="@item.Id"><i class="fa-solid fa-pencil m-r-5"></i> Düzenle</a>
                                    <!--Details Butonu-->
                                    <a class="dropdown-item" asp-controller="EmployeTimeOff" asp-action="DetailsTimeOff" asp-route-id="@item.Id"><i class="fa-solid fa-pencil m-r-5"></i>Detaylar</a>
                                    <!--Delete Butonu-->
                                    <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#delete_TimeOff_@item.Id"><i class="fa-regular fa-trash-can m-r-5"></i>Sil</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                        <!-- Delete Modal -->
                        <div class="modal custom-modal fade" id="delete_TimeOff_@item.Id" role="dialog">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-body">
                                        <div class="form-header">
                                            <h3>İzin Sil</h3>
                                            <p>Bu izin talebini silmek istediğinize emin misiniz?</p>
                                        </div>
                                        <div class="modal-btn delete-action">
                                            <div class="row">
                                                <div class="offset-2 col-3">
                                                    <!-- Delete Button with Form Submission -->
                                                    <form method="post" asp-controller="EmployeTimeOff" asp-action="Delete" asp-route-id="@item.Id">
                                                        <button type="submit" class="btn btn-primary"><i class="fa-regular fa-trash-can m-r-5"> </i> Sil</button>
                                                    </form>
                                                </div>
                                                <div class="offset-2 col-3">
                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa-regular fa-circle-xmark"></i>  İptal</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>