InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/SuperAdmin/Controllers/PackageController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MVC_ONION_PROJECT.APPLICATION.DTo_s.PackageDtos;
using MVC_ONION_PROJECT.APPLICATION.DTo_s.PackageDtos;
using MVC_ONION_PROJECT.APPLICATION.Services.PackageService;
using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.SuperAdmin.Models.Package;

namespace MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.SuperAdmin.Controllers
{
    public class PackageController : SuperAdminBaseController
    {
        private readonly IPackageService _packageService;
        private readonly IMapper _mapper;

        public PackageController(IPackageService packageService, IMapper mapper)
        {
            _packageService = packageService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var result=await _packageService.GetAllAsync();
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<List<PackageListVm>>( result.Data));
            }
            return View(_mapper.Map<List<PackageListVm>>(result.Data));
        }
        [HttpGet]
        public IActionResult AddPackage()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddPackage(PackageCreateVm model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var addResult = await _packageService.AddAsync(_mapper.Map<PackageCreateDto>(model));
            if (!addResult.IsSuccess)
            {
                ErrorNoty(addResult.Message);
                return View(model);
            }
            SuccessNoty(addResult.Message);
            return RedirectToAction("index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var result = await _packageService.DeleteAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return RedirectToAction(nameof(Index));
            }
            SuccessNoty(result.Message);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> EditPackage(Guid id)
        {
            var result = await _packageService.GetByIdAsync(id);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(_mapper.Map<PackageUpdateVm>(result.Data));
            }
            var packageEditVm = _mapper.Map<PackageUpdateVm>(result.Data);
            return View(packageEditVm);
        }
        [HttpPost]
        public async Task<IActionResult> EditPackage(PackageUpdateVm model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var packageeditdto = _mapper.Map<PackageUpdateDto>(model);
            var result = await _packageService.UpdateAsync(packageeditdto);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);
                return View(model);
            }
            SuccessNoty(result.Message);
            var resultVM = _mapper.Map<PackageUpdateVm>(result.Data);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> ActiveOrPasive(Guid Id, bool isActive)
        {
            var package = await _packageService.GetByIdAsync(Id);
            if (!ModelState.IsValid)
            {
                return View(package);
            }
            var PackageEditdto = _mapper.Map<PackageUpdateDto>(package.Data);
            PackageEditdto.IsActive = isActive;
            var result = await _packageService.UpdateAsync(PackageEditdto);
            if (!result.IsSuccess)
            {
                ErrorNoty(result.Message);

                return RedirectToAction(nameof(Index));

            }
            SuccessNoty(result.Message);
            return RedirectToAction(nameof(Index));

        }
    }
}

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/SuperAdmin/Views/Package/AddPackage.cshtml
@model MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.SuperAdmin.Models.Package.PackageCreateVm;
@{
    Layout = "_Layout";
}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Çalışan Maaşları</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="Paket" asp-action="Index">Paket Listesi</a></li>
                <li class="breadcrumb-item active">Paket Ekleme</li>
            </ul>
        </div>
    </div>
</div>
<form asp-area="SuperAdmin" enctype="multipart/form-data" asp-controller="Package" asp-action="AddPackage">
    <div class="row">
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="PackageName" class="control-label">
                </label>
                <input asp-for="PackageName" class="form-control" type="text">
                <span asp-validation-for="PackageName" class="text-danger"></span>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="Price" class="control-label">
                </label>
                <input asp-for="Price" class="form-control" type="number">
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="NumberOfUser" class="control-label">
                </label>
                <input asp-for="NumberOfUser" class="form-control" type="number">
                <span asp-validation-for="NumberOfUser" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="PackageDurationMonth" class="control-label">
                </label>
                <input asp-for="PackageDurationMonth" class="form-control" type="number">
                <span asp-validation-for="PackageDurationMonth" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <button class="btn btn-primary" type="submit"><i class="fa-solid fa-plus"></i> Kaydet</button>
        <a class="btn btn-secondary" asp-area="SuperAdmin" asp-controller="Package" asp-action="index"><i class="fa-regular fa-circle-xmark"></i>  İptal</a>
    </div>
</form>

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/SuperAdmin/Views/Package/EditPackage.cshtml
@model MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.SuperAdmin.Models.Package.PackageUpdateVm;
@{
    Layout = "_Layout";
}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Paket Güncelleme</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                <li class="breadcrumb-item"><a asp-controller="Package" asp-action="Index">Paket Listesi</a></li>
                <li class="breadcrumb-item active">Paket Güncelleme</li>
            </ul>
        </div>
    </div>
</div>
<form asp-area="SuperAdmin" enctype="multipart/form-data" asp-controller="Package" asp-action="EditPackage">
    <div class="row">
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="PackageName" class="control-label">
                </label>
                <input asp-for="PackageName" class="form-control" type="text">
                <input asp-for="Id" hidden class="form-control" type="text">
                <span asp-validation-for="PackageName" class="text-danger"></span>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="Price" class="control-label">
                </label>
                <input asp-for="Price" class="form-control" type="number">
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="NumberOfUser" class="control-label">
                </label>
                <input asp-for="NumberOfUser" class="form-control" type="number">
                <span asp-validation-for="NumberOfUser" class="text-danger"></span>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="input-block mb-3">
                <label asp-for="PackageDurationMonth" class="control-label">
                </label>
                <input asp-for="PackageDurationMonth" class="form-control" type="number">
                <span asp-validation-for="PackageDurationMonth" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-12">
        <button class="btn btn-primary" type="submit"><i class="fa-solid fa-plus"></i> Kaydet</button>
        <button class="btn btn-secondary" asp-area="SuperAdmin" asp-controller="Package" asp-action="index"><i class="fa-regular fa-circle-xmark"></i> İptal</button>
    </div>
</form>

InSightHR/MVC_ONION_PROJECT.PRESENTATION.IDENTITY/Areas/SuperAdmin/Views/Package/Index.cshtml
@using MVC_ONION_PROJECT.PRESENTATION.IDENTITY.Areas.SuperAdmin.Models.Package;
@model List<PackageListVm>;
@{
    Layout = "_Layout";
}


<div class="content container-fluid">

    <div class="page-header">
        <div class="row align-items-center">
            <div class="col">
                <h3 class="page-title">Paketler</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                    <li class="breadcrumb-item active">Paket Listesi</li>
                </ul>
            </div>
            <div class="col-auto float-end ms-auto">
                <a class="btn btn-secondary" asp-area="SuperAdmin" asp-controller="Package" asp-action="AddPackage"><i class="fa-solid fa-plus"></i>Paket Ekle</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 ml-8">

            @foreach (var item in Model)
            {

                <div class="columns ">

                    <ul class="price" id="@item.Id">

                        <input asp-for="@item.Id" id="basicPricepro_@item.Id" hidden value="@item.Id">
                        <li class="grey" style="background-color: #fd7960">
                            <div class="row">
                                <span class="offset-5 col-md-6 text-start">
                                    @item.PackageName
                                </span>

                                <span class="dropdown dropdown-action  col-md-1 ">
                                    <a href="#" class="action-icon dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><i class="material-icons">more_vert</i></a>
                                    <span class="dropdown-menu dropdown-menu-right">
                                        <!-- Edit Button -->
                                        <a class="dropdown-item" h asp-controller="Package" asp-action="EditPackage" asp-route-id="@item.Id"><i class="fa-solid fa-pencil m-r-5"></i>Güncelle</a>
                                        <!-- Delete Button -->
                                        <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#delete_packageSalary_@item.Id"><i class="fa-regular fa-trash-can m-r-5"></i> Delete</a>
                                    </span>
                                </span>
                            </div>
                        </li>
                        
                        <li>@item.NumberOfUser Kişiye kadar</li>
                        <li>@item.PackageDurationMonth Aylık Kullanım</li>
                        <li style="background-color:#fd7663">@item.Price $</li>
                        <li class="text-center">
                            <div class="dropdown action-label">
                                <a class="btn btn-white btn-sm btn-rounded dropdown-toggle" href="#"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa-regular fa-circle-dot @(item.IsActive ? "text-success" : "text-danger") "> <span style="font-family:Arial, sans-serif">@(item.IsActive ? "Active" : "Inactive")</span> </i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <form method="post" asp-controller="Package" asp-action="ActiveOrPasive" asp-route-id="@item.Id" asp-route-isActive="true">
                                        <button class="btn dropdown-item" type="submit">
                                            <i class="fa-regular fa-circle-dot text-success"></i>
                                            Active
                                        </button>
                                    </form>
                                    <form method="post" asp-controller="Package" asp-action="ActiveOrPasive" asp-route-id="@item.Id" asp-route-isActive="false">
                                        <button class="btn dropdown-item" type="submit">
                                            <i class="fa-regular fa-circle-dot text-danger"></i>
                                            Inactive
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </li>

                    </ul>

                    <!-- Delete Modal -->
                    <div class="modal custom-modal fade" id="delete_packageSalary_@item.Id" role="dialog">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <div class="form-header">
                                        <h3>Delete Asset</h3>
                                        <p>Are you sure you want to delete salary of @item.PackageName?</p>
                                    </div>
                                    <div class="modal-btn delete-action">
                                        <div class="row">
                                            <div class="offset-2 col-3">
                                                <!-- Delete Button with Form Submission -->
                                                <form method="post" asp-controller="Package" asp-action="Delete" asp-route-id="@item.Id">
                                                    <button type="submit" class="btn btn-primary">Delete</button>
                                                </form>
                                            </div>
                                            <div class="offset-2 col-3">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            }

        </div>
    </div>
</div>